### ISSUE TITLE
client Army has low cohesion

### ISSUE THREAD

**Issue by mbblau423** [PBeninga/GlobalWarming#107]
https://github.com/PBeninga/GlobalWarming/blob/dc3d327c80e5c613124686e1964628c2e16c2e87/client/army.js#L1

The army class has low cohesion because the constructor is both building the animations (which it should do) and building + displaying the army count (which can be done outside the constructor).

**Comment by jaketerrito** [comment]
This is exactly what a sprite is meant to do.
