### ISSUE TITLE
CURRENT TODO

### ISSUE THREAD

**Issue by LoumenaMax** [PBeninga/GlobalWarming#116]
Add a waiting window on the client main menu for logins
Add a process login function that instantiates player objects in app.js
Add a processlogin callback to onLogin in Login.js
Fix battles to movingArmy conversion, and what occurs when movingarmy encounters an army owned by the movingArmies player

**Comment by jaketerrito** [comment]
fix battle balancing.
Multi army battles.
Menu for volume.
mute buttons.
